### ISSUE TITLE
Error launching on mac

### ISSUE THREAD

**Issue by snil4** [TNG-dev/tachi-import-scripts#2]
I'm getting an error opening the app on macos (MBA m1), I did manage to open the app by going into the app content and opening the executable with the terminal but trying to open the app as it should be didn't work both on the .zip and .dmg versions.

The error prompt:

**A JavaScript error occurred in the main process**

Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir 'logs'
at Object.mkdirSync (node:fs:1324:3)
at File._createLogDirIfNotExist (/private/var/folders/18/r6610j9d32bdncdyy391f6j40000gn/T/AppTranslocation/197117F9-0EFF-400D-A786-C3E688F833CA/d/tachi-import-scripts.app/Contents/Resources/app.asar/node_modules/winston/lib/winston/transports/file.js:691:10)
at new File (/private/var/folders/18/r6610j9d32bdncdyy391f6j40000gn/T/AppTranslocation/197117F9-0EFF-400D-A786-C3E688F833CA/d/tachi-import-scripts.app/Contents/Resources/app.asar/node_modules/winston/lib/winston/transports/file.js:92:28)
at Object.<anonymous> (/private/var/folders/18/r6610j9d32bdncdyy391f6j40000gn/T/AppTranslocation/197117F9-0EFF-400D-A786-C3E688F833CA/d/tachi-import-scripts.app/Contents/Resources/app.asar/dist/node/util/logger.js:43:5)
at Module._compile (node:internal/modules/cjs/loader:1110:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1006:19)

**Comment by zkldi** [comment]
interesting. Looks like some sandbox nonsense from macOS.

**Comment by snil4** [comment]
I guess I'll share my workaround for now for those who run into the same problem, but I'm not closing the issue since it's just a workaround.

Right click the app > Show Package Contents > Contents > MacOS > launch the executable and it works as it should be.
